# This is a basic workflow to help you get started with Actions

name: Client Libs Backward Compatibility - New

on:
  push:
    paths-ignore:
      - 'README.md'
      - .github/workflows/skills-service-backward-compat.yml
      - .github/workflows/client-libs-backward-compat.yml
  pull_request:
    paths-ignore:
      - 'README.md'
      - .github/workflows/skills-service-backward-compat.yml
      - .github/workflows/client-libs-backward-compat.yml
  workflow_dispatch:

jobs:
  # ------------------------
  get_skills_service_versions:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          res=`curl -s https://api.github.com/repos/NationalSecurityAgency/skills-service/releases`
          echo $res
          VERSIONS='${{ toJSON(res.versions) }}'
          echo ::set-output name=versions::${VERSIONS}

  # ------------------------
  run_backward_compatibility_tests:
    runs-on: ubuntu-latest
    needs:
      - get_skills_service_versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get_skills_service_versions.outputs.versions) }}
    steps:
      - name: Matrix => (${{ matrix.version}})
        run: |
          echo ${{ matrix.version }}
